// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_friend.proto

#ifndef PROTOBUF_game_5ffriend_2eproto__INCLUDED
#define PROTOBUF_game_5ffriend_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "game_common.pb.h"
// @@protoc_insertion_point(includes)

namespace protocols {
namespace common {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_game_5ffriend_2eproto();
void protobuf_AssignDesc_game_5ffriend_2eproto();
void protobuf_ShutdownFile_game_5ffriend_2eproto();

class GetFriendListRequest;
class GetFriendListResponse;
class GetContactListRequest;
class GetContactListResponse;
class AddBlacklistRequest;
class AddBlacklistResponse;
class DeleteBlacklistRequest;
class DeleteBlacklistResponse;
class GetBlacklistRequest;
class GetBlacklistResponse;
class ApplyFriendRequest;
class ApplyFriendResponse;
class ApplyFriendNotify;
class AnswerFriendRequest;
class AnswerFriendResponse;
class AnswerFriendNotify;
class DeleteFriendRequest;
class DeleteFriendResponse;
class DeleteFriendNotify;
class FriendStatusNotify;
class FindPlayerRequest;
class FindPlayerResponse;

// ===================================================================

class GetFriendListRequest : public ::google::protobuf::Message {
 public:
  GetFriendListRequest();
  virtual ~GetFriendListRequest();
  
  GetFriendListRequest(const GetFriendListRequest& from);
  
  inline GetFriendListRequest& operator=(const GetFriendListRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetFriendListRequest& default_instance();
  
  void Swap(GetFriendListRequest* other);
  
  // implements Message ----------------------------------------------
  
  GetFriendListRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetFriendListRequest& from);
  void MergeFrom(const GetFriendListRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:protocols.common.GetFriendListRequest)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static GetFriendListRequest* default_instance_;
};
// -------------------------------------------------------------------

class GetFriendListResponse : public ::google::protobuf::Message {
 public:
  GetFriendListResponse();
  virtual ~GetFriendListResponse();
  
  GetFriendListResponse(const GetFriendListResponse& from);
  
  inline GetFriendListResponse& operator=(const GetFriendListResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetFriendListResponse& default_instance();
  
  void Swap(GetFriendListResponse* other);
  
  // implements Message ----------------------------------------------
  
  GetFriendListResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetFriendListResponse& from);
  void MergeFrom(const GetFriendListResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 error_code = 1;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::int32 error_code() const;
  inline void set_error_code(::google::protobuf::int32 value);
  
  // repeated .protocols.common.PlayerInfo player_list = 2;
  inline int player_list_size() const;
  inline void clear_player_list();
  static const int kPlayerListFieldNumber = 2;
  inline const ::protocols::common::PlayerInfo& player_list(int index) const;
  inline ::protocols::common::PlayerInfo* mutable_player_list(int index);
  inline ::protocols::common::PlayerInfo* add_player_list();
  inline const ::google::protobuf::RepeatedPtrField< ::protocols::common::PlayerInfo >&
      player_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::protocols::common::PlayerInfo >*
      mutable_player_list();
  
  // @@protoc_insertion_point(class_scope:protocols.common.GetFriendListResponse)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::protocols::common::PlayerInfo > player_list_;
  ::google::protobuf::int32 error_code_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static GetFriendListResponse* default_instance_;
};
// -------------------------------------------------------------------

class GetContactListRequest : public ::google::protobuf::Message {
 public:
  GetContactListRequest();
  virtual ~GetContactListRequest();
  
  GetContactListRequest(const GetContactListRequest& from);
  
  inline GetContactListRequest& operator=(const GetContactListRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetContactListRequest& default_instance();
  
  void Swap(GetContactListRequest* other);
  
  // implements Message ----------------------------------------------
  
  GetContactListRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetContactListRequest& from);
  void MergeFrom(const GetContactListRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:protocols.common.GetContactListRequest)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static GetContactListRequest* default_instance_;
};
// -------------------------------------------------------------------

class GetContactListResponse : public ::google::protobuf::Message {
 public:
  GetContactListResponse();
  virtual ~GetContactListResponse();
  
  GetContactListResponse(const GetContactListResponse& from);
  
  inline GetContactListResponse& operator=(const GetContactListResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetContactListResponse& default_instance();
  
  void Swap(GetContactListResponse* other);
  
  // implements Message ----------------------------------------------
  
  GetContactListResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetContactListResponse& from);
  void MergeFrom(const GetContactListResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 error_code = 1;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::int32 error_code() const;
  inline void set_error_code(::google::protobuf::int32 value);
  
  // repeated .protocols.common.PlayerInfo player_list = 2;
  inline int player_list_size() const;
  inline void clear_player_list();
  static const int kPlayerListFieldNumber = 2;
  inline const ::protocols::common::PlayerInfo& player_list(int index) const;
  inline ::protocols::common::PlayerInfo* mutable_player_list(int index);
  inline ::protocols::common::PlayerInfo* add_player_list();
  inline const ::google::protobuf::RepeatedPtrField< ::protocols::common::PlayerInfo >&
      player_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::protocols::common::PlayerInfo >*
      mutable_player_list();
  
  // @@protoc_insertion_point(class_scope:protocols.common.GetContactListResponse)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::protocols::common::PlayerInfo > player_list_;
  ::google::protobuf::int32 error_code_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static GetContactListResponse* default_instance_;
};
// -------------------------------------------------------------------

class AddBlacklistRequest : public ::google::protobuf::Message {
 public:
  AddBlacklistRequest();
  virtual ~AddBlacklistRequest();
  
  AddBlacklistRequest(const AddBlacklistRequest& from);
  
  inline AddBlacklistRequest& operator=(const AddBlacklistRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const AddBlacklistRequest& default_instance();
  
  void Swap(AddBlacklistRequest* other);
  
  // implements Message ----------------------------------------------
  
  AddBlacklistRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AddBlacklistRequest& from);
  void MergeFrom(const AddBlacklistRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int64 dst_guid = 1;
  inline bool has_dst_guid() const;
  inline void clear_dst_guid();
  static const int kDstGuidFieldNumber = 1;
  inline ::google::protobuf::int64 dst_guid() const;
  inline void set_dst_guid(::google::protobuf::int64 value);
  
  // @@protoc_insertion_point(class_scope:protocols.common.AddBlacklistRequest)
 private:
  inline void set_has_dst_guid();
  inline void clear_has_dst_guid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 dst_guid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static AddBlacklistRequest* default_instance_;
};
// -------------------------------------------------------------------

class AddBlacklistResponse : public ::google::protobuf::Message {
 public:
  AddBlacklistResponse();
  virtual ~AddBlacklistResponse();
  
  AddBlacklistResponse(const AddBlacklistResponse& from);
  
  inline AddBlacklistResponse& operator=(const AddBlacklistResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const AddBlacklistResponse& default_instance();
  
  void Swap(AddBlacklistResponse* other);
  
  // implements Message ----------------------------------------------
  
  AddBlacklistResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AddBlacklistResponse& from);
  void MergeFrom(const AddBlacklistResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 error_code = 1;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::int32 error_code() const;
  inline void set_error_code(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:protocols.common.AddBlacklistResponse)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 error_code_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static AddBlacklistResponse* default_instance_;
};
// -------------------------------------------------------------------

class DeleteBlacklistRequest : public ::google::protobuf::Message {
 public:
  DeleteBlacklistRequest();
  virtual ~DeleteBlacklistRequest();
  
  DeleteBlacklistRequest(const DeleteBlacklistRequest& from);
  
  inline DeleteBlacklistRequest& operator=(const DeleteBlacklistRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeleteBlacklistRequest& default_instance();
  
  void Swap(DeleteBlacklistRequest* other);
  
  // implements Message ----------------------------------------------
  
  DeleteBlacklistRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DeleteBlacklistRequest& from);
  void MergeFrom(const DeleteBlacklistRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int64 dst_guid = 1;
  inline bool has_dst_guid() const;
  inline void clear_dst_guid();
  static const int kDstGuidFieldNumber = 1;
  inline ::google::protobuf::int64 dst_guid() const;
  inline void set_dst_guid(::google::protobuf::int64 value);
  
  // @@protoc_insertion_point(class_scope:protocols.common.DeleteBlacklistRequest)
 private:
  inline void set_has_dst_guid();
  inline void clear_has_dst_guid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 dst_guid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static DeleteBlacklistRequest* default_instance_;
};
// -------------------------------------------------------------------

class DeleteBlacklistResponse : public ::google::protobuf::Message {
 public:
  DeleteBlacklistResponse();
  virtual ~DeleteBlacklistResponse();
  
  DeleteBlacklistResponse(const DeleteBlacklistResponse& from);
  
  inline DeleteBlacklistResponse& operator=(const DeleteBlacklistResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeleteBlacklistResponse& default_instance();
  
  void Swap(DeleteBlacklistResponse* other);
  
  // implements Message ----------------------------------------------
  
  DeleteBlacklistResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DeleteBlacklistResponse& from);
  void MergeFrom(const DeleteBlacklistResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 error_code = 1;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::int32 error_code() const;
  inline void set_error_code(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:protocols.common.DeleteBlacklistResponse)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 error_code_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static DeleteBlacklistResponse* default_instance_;
};
// -------------------------------------------------------------------

class GetBlacklistRequest : public ::google::protobuf::Message {
 public:
  GetBlacklistRequest();
  virtual ~GetBlacklistRequest();
  
  GetBlacklistRequest(const GetBlacklistRequest& from);
  
  inline GetBlacklistRequest& operator=(const GetBlacklistRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetBlacklistRequest& default_instance();
  
  void Swap(GetBlacklistRequest* other);
  
  // implements Message ----------------------------------------------
  
  GetBlacklistRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetBlacklistRequest& from);
  void MergeFrom(const GetBlacklistRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:protocols.common.GetBlacklistRequest)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static GetBlacklistRequest* default_instance_;
};
// -------------------------------------------------------------------

class GetBlacklistResponse : public ::google::protobuf::Message {
 public:
  GetBlacklistResponse();
  virtual ~GetBlacklistResponse();
  
  GetBlacklistResponse(const GetBlacklistResponse& from);
  
  inline GetBlacklistResponse& operator=(const GetBlacklistResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetBlacklistResponse& default_instance();
  
  void Swap(GetBlacklistResponse* other);
  
  // implements Message ----------------------------------------------
  
  GetBlacklistResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetBlacklistResponse& from);
  void MergeFrom(const GetBlacklistResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 error_code = 1;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::int32 error_code() const;
  inline void set_error_code(::google::protobuf::int32 value);
  
  // repeated .protocols.common.PlayerInfo player_list = 2;
  inline int player_list_size() const;
  inline void clear_player_list();
  static const int kPlayerListFieldNumber = 2;
  inline const ::protocols::common::PlayerInfo& player_list(int index) const;
  inline ::protocols::common::PlayerInfo* mutable_player_list(int index);
  inline ::protocols::common::PlayerInfo* add_player_list();
  inline const ::google::protobuf::RepeatedPtrField< ::protocols::common::PlayerInfo >&
      player_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::protocols::common::PlayerInfo >*
      mutable_player_list();
  
  // @@protoc_insertion_point(class_scope:protocols.common.GetBlacklistResponse)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::protocols::common::PlayerInfo > player_list_;
  ::google::protobuf::int32 error_code_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static GetBlacklistResponse* default_instance_;
};
// -------------------------------------------------------------------

class ApplyFriendRequest : public ::google::protobuf::Message {
 public:
  ApplyFriendRequest();
  virtual ~ApplyFriendRequest();
  
  ApplyFriendRequest(const ApplyFriendRequest& from);
  
  inline ApplyFriendRequest& operator=(const ApplyFriendRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ApplyFriendRequest& default_instance();
  
  void Swap(ApplyFriendRequest* other);
  
  // implements Message ----------------------------------------------
  
  ApplyFriendRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ApplyFriendRequest& from);
  void MergeFrom(const ApplyFriendRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int64 dst_guid = 1;
  inline bool has_dst_guid() const;
  inline void clear_dst_guid();
  static const int kDstGuidFieldNumber = 1;
  inline ::google::protobuf::int64 dst_guid() const;
  inline void set_dst_guid(::google::protobuf::int64 value);
  
  // @@protoc_insertion_point(class_scope:protocols.common.ApplyFriendRequest)
 private:
  inline void set_has_dst_guid();
  inline void clear_has_dst_guid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 dst_guid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static ApplyFriendRequest* default_instance_;
};
// -------------------------------------------------------------------

class ApplyFriendResponse : public ::google::protobuf::Message {
 public:
  ApplyFriendResponse();
  virtual ~ApplyFriendResponse();
  
  ApplyFriendResponse(const ApplyFriendResponse& from);
  
  inline ApplyFriendResponse& operator=(const ApplyFriendResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ApplyFriendResponse& default_instance();
  
  void Swap(ApplyFriendResponse* other);
  
  // implements Message ----------------------------------------------
  
  ApplyFriendResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ApplyFriendResponse& from);
  void MergeFrom(const ApplyFriendResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 error_code = 1;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::int32 error_code() const;
  inline void set_error_code(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:protocols.common.ApplyFriendResponse)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 error_code_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static ApplyFriendResponse* default_instance_;
};
// -------------------------------------------------------------------

class ApplyFriendNotify : public ::google::protobuf::Message {
 public:
  ApplyFriendNotify();
  virtual ~ApplyFriendNotify();
  
  ApplyFriendNotify(const ApplyFriendNotify& from);
  
  inline ApplyFriendNotify& operator=(const ApplyFriendNotify& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ApplyFriendNotify& default_instance();
  
  void Swap(ApplyFriendNotify* other);
  
  // implements Message ----------------------------------------------
  
  ApplyFriendNotify* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ApplyFriendNotify& from);
  void MergeFrom(const ApplyFriendNotify& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int64 src_guid = 1;
  inline bool has_src_guid() const;
  inline void clear_src_guid();
  static const int kSrcGuidFieldNumber = 1;
  inline ::google::protobuf::int64 src_guid() const;
  inline void set_src_guid(::google::protobuf::int64 value);
  
  // optional string src_name = 2;
  inline bool has_src_name() const;
  inline void clear_src_name();
  static const int kSrcNameFieldNumber = 2;
  inline const ::std::string& src_name() const;
  inline void set_src_name(const ::std::string& value);
  inline void set_src_name(const char* value);
  inline void set_src_name(const char* value, size_t size);
  inline ::std::string* mutable_src_name();
  inline ::std::string* release_src_name();
  
  // optional int32 src_server_id = 3;
  inline bool has_src_server_id() const;
  inline void clear_src_server_id();
  static const int kSrcServerIdFieldNumber = 3;
  inline ::google::protobuf::int32 src_server_id() const;
  inline void set_src_server_id(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:protocols.common.ApplyFriendNotify)
 private:
  inline void set_has_src_guid();
  inline void clear_has_src_guid();
  inline void set_has_src_name();
  inline void clear_has_src_name();
  inline void set_has_src_server_id();
  inline void clear_has_src_server_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 src_guid_;
  ::std::string* src_name_;
  ::google::protobuf::int32 src_server_id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static ApplyFriendNotify* default_instance_;
};
// -------------------------------------------------------------------

class AnswerFriendRequest : public ::google::protobuf::Message {
 public:
  AnswerFriendRequest();
  virtual ~AnswerFriendRequest();
  
  AnswerFriendRequest(const AnswerFriendRequest& from);
  
  inline AnswerFriendRequest& operator=(const AnswerFriendRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const AnswerFriendRequest& default_instance();
  
  void Swap(AnswerFriendRequest* other);
  
  // implements Message ----------------------------------------------
  
  AnswerFriendRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AnswerFriendRequest& from);
  void MergeFrom(const AnswerFriendRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int64 src_guid = 1;
  inline bool has_src_guid() const;
  inline void clear_src_guid();
  static const int kSrcGuidFieldNumber = 1;
  inline ::google::protobuf::int64 src_guid() const;
  inline void set_src_guid(::google::protobuf::int64 value);
  
  // required bool accept_flag = 2;
  inline bool has_accept_flag() const;
  inline void clear_accept_flag();
  static const int kAcceptFlagFieldNumber = 2;
  inline bool accept_flag() const;
  inline void set_accept_flag(bool value);
  
  // @@protoc_insertion_point(class_scope:protocols.common.AnswerFriendRequest)
 private:
  inline void set_has_src_guid();
  inline void clear_has_src_guid();
  inline void set_has_accept_flag();
  inline void clear_has_accept_flag();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 src_guid_;
  bool accept_flag_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static AnswerFriendRequest* default_instance_;
};
// -------------------------------------------------------------------

class AnswerFriendResponse : public ::google::protobuf::Message {
 public:
  AnswerFriendResponse();
  virtual ~AnswerFriendResponse();
  
  AnswerFriendResponse(const AnswerFriendResponse& from);
  
  inline AnswerFriendResponse& operator=(const AnswerFriendResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const AnswerFriendResponse& default_instance();
  
  void Swap(AnswerFriendResponse* other);
  
  // implements Message ----------------------------------------------
  
  AnswerFriendResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AnswerFriendResponse& from);
  void MergeFrom(const AnswerFriendResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 error_code = 1;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::int32 error_code() const;
  inline void set_error_code(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:protocols.common.AnswerFriendResponse)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 error_code_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static AnswerFriendResponse* default_instance_;
};
// -------------------------------------------------------------------

class AnswerFriendNotify : public ::google::protobuf::Message {
 public:
  AnswerFriendNotify();
  virtual ~AnswerFriendNotify();
  
  AnswerFriendNotify(const AnswerFriendNotify& from);
  
  inline AnswerFriendNotify& operator=(const AnswerFriendNotify& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const AnswerFriendNotify& default_instance();
  
  void Swap(AnswerFriendNotify* other);
  
  // implements Message ----------------------------------------------
  
  AnswerFriendNotify* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AnswerFriendNotify& from);
  void MergeFrom(const AnswerFriendNotify& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int64 dst_guid = 1;
  inline bool has_dst_guid() const;
  inline void clear_dst_guid();
  static const int kDstGuidFieldNumber = 1;
  inline ::google::protobuf::int64 dst_guid() const;
  inline void set_dst_guid(::google::protobuf::int64 value);
  
  // required bool accept_flag = 2;
  inline bool has_accept_flag() const;
  inline void clear_accept_flag();
  static const int kAcceptFlagFieldNumber = 2;
  inline bool accept_flag() const;
  inline void set_accept_flag(bool value);
  
  // optional string dst_name = 3;
  inline bool has_dst_name() const;
  inline void clear_dst_name();
  static const int kDstNameFieldNumber = 3;
  inline const ::std::string& dst_name() const;
  inline void set_dst_name(const ::std::string& value);
  inline void set_dst_name(const char* value);
  inline void set_dst_name(const char* value, size_t size);
  inline ::std::string* mutable_dst_name();
  inline ::std::string* release_dst_name();
  
  // optional int32 dst_server_id = 4;
  inline bool has_dst_server_id() const;
  inline void clear_dst_server_id();
  static const int kDstServerIdFieldNumber = 4;
  inline ::google::protobuf::int32 dst_server_id() const;
  inline void set_dst_server_id(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:protocols.common.AnswerFriendNotify)
 private:
  inline void set_has_dst_guid();
  inline void clear_has_dst_guid();
  inline void set_has_accept_flag();
  inline void clear_has_accept_flag();
  inline void set_has_dst_name();
  inline void clear_has_dst_name();
  inline void set_has_dst_server_id();
  inline void clear_has_dst_server_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 dst_guid_;
  ::std::string* dst_name_;
  bool accept_flag_;
  ::google::protobuf::int32 dst_server_id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static AnswerFriendNotify* default_instance_;
};
// -------------------------------------------------------------------

class DeleteFriendRequest : public ::google::protobuf::Message {
 public:
  DeleteFriendRequest();
  virtual ~DeleteFriendRequest();
  
  DeleteFriendRequest(const DeleteFriendRequest& from);
  
  inline DeleteFriendRequest& operator=(const DeleteFriendRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeleteFriendRequest& default_instance();
  
  void Swap(DeleteFriendRequest* other);
  
  // implements Message ----------------------------------------------
  
  DeleteFriendRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DeleteFriendRequest& from);
  void MergeFrom(const DeleteFriendRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int64 dst_guid = 1;
  inline bool has_dst_guid() const;
  inline void clear_dst_guid();
  static const int kDstGuidFieldNumber = 1;
  inline ::google::protobuf::int64 dst_guid() const;
  inline void set_dst_guid(::google::protobuf::int64 value);
  
  // @@protoc_insertion_point(class_scope:protocols.common.DeleteFriendRequest)
 private:
  inline void set_has_dst_guid();
  inline void clear_has_dst_guid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 dst_guid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static DeleteFriendRequest* default_instance_;
};
// -------------------------------------------------------------------

class DeleteFriendResponse : public ::google::protobuf::Message {
 public:
  DeleteFriendResponse();
  virtual ~DeleteFriendResponse();
  
  DeleteFriendResponse(const DeleteFriendResponse& from);
  
  inline DeleteFriendResponse& operator=(const DeleteFriendResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeleteFriendResponse& default_instance();
  
  void Swap(DeleteFriendResponse* other);
  
  // implements Message ----------------------------------------------
  
  DeleteFriendResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DeleteFriendResponse& from);
  void MergeFrom(const DeleteFriendResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 error_code = 1;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::int32 error_code() const;
  inline void set_error_code(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:protocols.common.DeleteFriendResponse)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 error_code_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static DeleteFriendResponse* default_instance_;
};
// -------------------------------------------------------------------

class DeleteFriendNotify : public ::google::protobuf::Message {
 public:
  DeleteFriendNotify();
  virtual ~DeleteFriendNotify();
  
  DeleteFriendNotify(const DeleteFriendNotify& from);
  
  inline DeleteFriendNotify& operator=(const DeleteFriendNotify& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeleteFriendNotify& default_instance();
  
  void Swap(DeleteFriendNotify* other);
  
  // implements Message ----------------------------------------------
  
  DeleteFriendNotify* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DeleteFriendNotify& from);
  void MergeFrom(const DeleteFriendNotify& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int64 src_guid = 1;
  inline bool has_src_guid() const;
  inline void clear_src_guid();
  static const int kSrcGuidFieldNumber = 1;
  inline ::google::protobuf::int64 src_guid() const;
  inline void set_src_guid(::google::protobuf::int64 value);
  
  // @@protoc_insertion_point(class_scope:protocols.common.DeleteFriendNotify)
 private:
  inline void set_has_src_guid();
  inline void clear_has_src_guid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 src_guid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static DeleteFriendNotify* default_instance_;
};
// -------------------------------------------------------------------

class FriendStatusNotify : public ::google::protobuf::Message {
 public:
  FriendStatusNotify();
  virtual ~FriendStatusNotify();
  
  FriendStatusNotify(const FriendStatusNotify& from);
  
  inline FriendStatusNotify& operator=(const FriendStatusNotify& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const FriendStatusNotify& default_instance();
  
  void Swap(FriendStatusNotify* other);
  
  // implements Message ----------------------------------------------
  
  FriendStatusNotify* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FriendStatusNotify& from);
  void MergeFrom(const FriendStatusNotify& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int64 guid = 1;
  inline bool has_guid() const;
  inline void clear_guid();
  static const int kGuidFieldNumber = 1;
  inline ::google::protobuf::int64 guid() const;
  inline void set_guid(::google::protobuf::int64 value);
  
  // optional int32 status = 2;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 2;
  inline ::google::protobuf::int32 status() const;
  inline void set_status(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:protocols.common.FriendStatusNotify)
 private:
  inline void set_has_guid();
  inline void clear_has_guid();
  inline void set_has_status();
  inline void clear_has_status();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 guid_;
  ::google::protobuf::int32 status_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static FriendStatusNotify* default_instance_;
};
// -------------------------------------------------------------------

class FindPlayerRequest : public ::google::protobuf::Message {
 public:
  FindPlayerRequest();
  virtual ~FindPlayerRequest();
  
  FindPlayerRequest(const FindPlayerRequest& from);
  
  inline FindPlayerRequest& operator=(const FindPlayerRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const FindPlayerRequest& default_instance();
  
  void Swap(FindPlayerRequest* other);
  
  // implements Message ----------------------------------------------
  
  FindPlayerRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FindPlayerRequest& from);
  void MergeFrom(const FindPlayerRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // @@protoc_insertion_point(class_scope:protocols.common.FindPlayerRequest)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* name_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static FindPlayerRequest* default_instance_;
};
// -------------------------------------------------------------------

class FindPlayerResponse : public ::google::protobuf::Message {
 public:
  FindPlayerResponse();
  virtual ~FindPlayerResponse();
  
  FindPlayerResponse(const FindPlayerResponse& from);
  
  inline FindPlayerResponse& operator=(const FindPlayerResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const FindPlayerResponse& default_instance();
  
  void Swap(FindPlayerResponse* other);
  
  // implements Message ----------------------------------------------
  
  FindPlayerResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FindPlayerResponse& from);
  void MergeFrom(const FindPlayerResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 error_code = 1;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::int32 error_code() const;
  inline void set_error_code(::google::protobuf::int32 value);
  
  // repeated int64 guid_list = 2;
  inline int guid_list_size() const;
  inline void clear_guid_list();
  static const int kGuidListFieldNumber = 2;
  inline ::google::protobuf::int64 guid_list(int index) const;
  inline void set_guid_list(int index, ::google::protobuf::int64 value);
  inline void add_guid_list(::google::protobuf::int64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      guid_list() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_guid_list();
  
  // @@protoc_insertion_point(class_scope:protocols.common.FindPlayerResponse)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > guid_list_;
  ::google::protobuf::int32 error_code_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5ffriend_2eproto();
  friend void protobuf_AssignDesc_game_5ffriend_2eproto();
  friend void protobuf_ShutdownFile_game_5ffriend_2eproto();
  
  void InitAsDefaultInstance();
  static FindPlayerResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// GetFriendListRequest

// -------------------------------------------------------------------

// GetFriendListResponse

// required int32 error_code = 1;
inline bool GetFriendListResponse::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetFriendListResponse::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetFriendListResponse::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetFriendListResponse::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 GetFriendListResponse::error_code() const {
  return error_code_;
}
inline void GetFriendListResponse::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
}

// repeated .protocols.common.PlayerInfo player_list = 2;
inline int GetFriendListResponse::player_list_size() const {
  return player_list_.size();
}
inline void GetFriendListResponse::clear_player_list() {
  player_list_.Clear();
}
inline const ::protocols::common::PlayerInfo& GetFriendListResponse::player_list(int index) const {
  return player_list_.Get(index);
}
inline ::protocols::common::PlayerInfo* GetFriendListResponse::mutable_player_list(int index) {
  return player_list_.Mutable(index);
}
inline ::protocols::common::PlayerInfo* GetFriendListResponse::add_player_list() {
  return player_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::protocols::common::PlayerInfo >&
GetFriendListResponse::player_list() const {
  return player_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::protocols::common::PlayerInfo >*
GetFriendListResponse::mutable_player_list() {
  return &player_list_;
}

// -------------------------------------------------------------------

// GetContactListRequest

// -------------------------------------------------------------------

// GetContactListResponse

// required int32 error_code = 1;
inline bool GetContactListResponse::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetContactListResponse::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetContactListResponse::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetContactListResponse::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 GetContactListResponse::error_code() const {
  return error_code_;
}
inline void GetContactListResponse::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
}

// repeated .protocols.common.PlayerInfo player_list = 2;
inline int GetContactListResponse::player_list_size() const {
  return player_list_.size();
}
inline void GetContactListResponse::clear_player_list() {
  player_list_.Clear();
}
inline const ::protocols::common::PlayerInfo& GetContactListResponse::player_list(int index) const {
  return player_list_.Get(index);
}
inline ::protocols::common::PlayerInfo* GetContactListResponse::mutable_player_list(int index) {
  return player_list_.Mutable(index);
}
inline ::protocols::common::PlayerInfo* GetContactListResponse::add_player_list() {
  return player_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::protocols::common::PlayerInfo >&
GetContactListResponse::player_list() const {
  return player_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::protocols::common::PlayerInfo >*
GetContactListResponse::mutable_player_list() {
  return &player_list_;
}

// -------------------------------------------------------------------

// AddBlacklistRequest

// required int64 dst_guid = 1;
inline bool AddBlacklistRequest::has_dst_guid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AddBlacklistRequest::set_has_dst_guid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AddBlacklistRequest::clear_has_dst_guid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AddBlacklistRequest::clear_dst_guid() {
  dst_guid_ = GOOGLE_LONGLONG(0);
  clear_has_dst_guid();
}
inline ::google::protobuf::int64 AddBlacklistRequest::dst_guid() const {
  return dst_guid_;
}
inline void AddBlacklistRequest::set_dst_guid(::google::protobuf::int64 value) {
  set_has_dst_guid();
  dst_guid_ = value;
}

// -------------------------------------------------------------------

// AddBlacklistResponse

// required int32 error_code = 1;
inline bool AddBlacklistResponse::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AddBlacklistResponse::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AddBlacklistResponse::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AddBlacklistResponse::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 AddBlacklistResponse::error_code() const {
  return error_code_;
}
inline void AddBlacklistResponse::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
}

// -------------------------------------------------------------------

// DeleteBlacklistRequest

// required int64 dst_guid = 1;
inline bool DeleteBlacklistRequest::has_dst_guid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DeleteBlacklistRequest::set_has_dst_guid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DeleteBlacklistRequest::clear_has_dst_guid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DeleteBlacklistRequest::clear_dst_guid() {
  dst_guid_ = GOOGLE_LONGLONG(0);
  clear_has_dst_guid();
}
inline ::google::protobuf::int64 DeleteBlacklistRequest::dst_guid() const {
  return dst_guid_;
}
inline void DeleteBlacklistRequest::set_dst_guid(::google::protobuf::int64 value) {
  set_has_dst_guid();
  dst_guid_ = value;
}

// -------------------------------------------------------------------

// DeleteBlacklistResponse

// required int32 error_code = 1;
inline bool DeleteBlacklistResponse::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DeleteBlacklistResponse::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DeleteBlacklistResponse::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DeleteBlacklistResponse::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 DeleteBlacklistResponse::error_code() const {
  return error_code_;
}
inline void DeleteBlacklistResponse::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
}

// -------------------------------------------------------------------

// GetBlacklistRequest

// -------------------------------------------------------------------

// GetBlacklistResponse

// required int32 error_code = 1;
inline bool GetBlacklistResponse::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetBlacklistResponse::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetBlacklistResponse::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetBlacklistResponse::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 GetBlacklistResponse::error_code() const {
  return error_code_;
}
inline void GetBlacklistResponse::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
}

// repeated .protocols.common.PlayerInfo player_list = 2;
inline int GetBlacklistResponse::player_list_size() const {
  return player_list_.size();
}
inline void GetBlacklistResponse::clear_player_list() {
  player_list_.Clear();
}
inline const ::protocols::common::PlayerInfo& GetBlacklistResponse::player_list(int index) const {
  return player_list_.Get(index);
}
inline ::protocols::common::PlayerInfo* GetBlacklistResponse::mutable_player_list(int index) {
  return player_list_.Mutable(index);
}
inline ::protocols::common::PlayerInfo* GetBlacklistResponse::add_player_list() {
  return player_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::protocols::common::PlayerInfo >&
GetBlacklistResponse::player_list() const {
  return player_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::protocols::common::PlayerInfo >*
GetBlacklistResponse::mutable_player_list() {
  return &player_list_;
}

// -------------------------------------------------------------------

// ApplyFriendRequest

// required int64 dst_guid = 1;
inline bool ApplyFriendRequest::has_dst_guid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ApplyFriendRequest::set_has_dst_guid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ApplyFriendRequest::clear_has_dst_guid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ApplyFriendRequest::clear_dst_guid() {
  dst_guid_ = GOOGLE_LONGLONG(0);
  clear_has_dst_guid();
}
inline ::google::protobuf::int64 ApplyFriendRequest::dst_guid() const {
  return dst_guid_;
}
inline void ApplyFriendRequest::set_dst_guid(::google::protobuf::int64 value) {
  set_has_dst_guid();
  dst_guid_ = value;
}

// -------------------------------------------------------------------

// ApplyFriendResponse

// required int32 error_code = 1;
inline bool ApplyFriendResponse::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ApplyFriendResponse::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ApplyFriendResponse::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ApplyFriendResponse::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 ApplyFriendResponse::error_code() const {
  return error_code_;
}
inline void ApplyFriendResponse::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
}

// -------------------------------------------------------------------

// ApplyFriendNotify

// required int64 src_guid = 1;
inline bool ApplyFriendNotify::has_src_guid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ApplyFriendNotify::set_has_src_guid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ApplyFriendNotify::clear_has_src_guid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ApplyFriendNotify::clear_src_guid() {
  src_guid_ = GOOGLE_LONGLONG(0);
  clear_has_src_guid();
}
inline ::google::protobuf::int64 ApplyFriendNotify::src_guid() const {
  return src_guid_;
}
inline void ApplyFriendNotify::set_src_guid(::google::protobuf::int64 value) {
  set_has_src_guid();
  src_guid_ = value;
}

// optional string src_name = 2;
inline bool ApplyFriendNotify::has_src_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ApplyFriendNotify::set_has_src_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ApplyFriendNotify::clear_has_src_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ApplyFriendNotify::clear_src_name() {
  if (src_name_ != &::google::protobuf::internal::kEmptyString) {
    src_name_->clear();
  }
  clear_has_src_name();
}
inline const ::std::string& ApplyFriendNotify::src_name() const {
  return *src_name_;
}
inline void ApplyFriendNotify::set_src_name(const ::std::string& value) {
  set_has_src_name();
  if (src_name_ == &::google::protobuf::internal::kEmptyString) {
    src_name_ = new ::std::string;
  }
  src_name_->assign(value);
}
inline void ApplyFriendNotify::set_src_name(const char* value) {
  set_has_src_name();
  if (src_name_ == &::google::protobuf::internal::kEmptyString) {
    src_name_ = new ::std::string;
  }
  src_name_->assign(value);
}
inline void ApplyFriendNotify::set_src_name(const char* value, size_t size) {
  set_has_src_name();
  if (src_name_ == &::google::protobuf::internal::kEmptyString) {
    src_name_ = new ::std::string;
  }
  src_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ApplyFriendNotify::mutable_src_name() {
  set_has_src_name();
  if (src_name_ == &::google::protobuf::internal::kEmptyString) {
    src_name_ = new ::std::string;
  }
  return src_name_;
}
inline ::std::string* ApplyFriendNotify::release_src_name() {
  clear_has_src_name();
  if (src_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = src_name_;
    src_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional int32 src_server_id = 3;
inline bool ApplyFriendNotify::has_src_server_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ApplyFriendNotify::set_has_src_server_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ApplyFriendNotify::clear_has_src_server_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ApplyFriendNotify::clear_src_server_id() {
  src_server_id_ = 0;
  clear_has_src_server_id();
}
inline ::google::protobuf::int32 ApplyFriendNotify::src_server_id() const {
  return src_server_id_;
}
inline void ApplyFriendNotify::set_src_server_id(::google::protobuf::int32 value) {
  set_has_src_server_id();
  src_server_id_ = value;
}

// -------------------------------------------------------------------

// AnswerFriendRequest

// required int64 src_guid = 1;
inline bool AnswerFriendRequest::has_src_guid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AnswerFriendRequest::set_has_src_guid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AnswerFriendRequest::clear_has_src_guid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AnswerFriendRequest::clear_src_guid() {
  src_guid_ = GOOGLE_LONGLONG(0);
  clear_has_src_guid();
}
inline ::google::protobuf::int64 AnswerFriendRequest::src_guid() const {
  return src_guid_;
}
inline void AnswerFriendRequest::set_src_guid(::google::protobuf::int64 value) {
  set_has_src_guid();
  src_guid_ = value;
}

// required bool accept_flag = 2;
inline bool AnswerFriendRequest::has_accept_flag() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AnswerFriendRequest::set_has_accept_flag() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AnswerFriendRequest::clear_has_accept_flag() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AnswerFriendRequest::clear_accept_flag() {
  accept_flag_ = false;
  clear_has_accept_flag();
}
inline bool AnswerFriendRequest::accept_flag() const {
  return accept_flag_;
}
inline void AnswerFriendRequest::set_accept_flag(bool value) {
  set_has_accept_flag();
  accept_flag_ = value;
}

// -------------------------------------------------------------------

// AnswerFriendResponse

// required int32 error_code = 1;
inline bool AnswerFriendResponse::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AnswerFriendResponse::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AnswerFriendResponse::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AnswerFriendResponse::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 AnswerFriendResponse::error_code() const {
  return error_code_;
}
inline void AnswerFriendResponse::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
}

// -------------------------------------------------------------------

// AnswerFriendNotify

// required int64 dst_guid = 1;
inline bool AnswerFriendNotify::has_dst_guid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AnswerFriendNotify::set_has_dst_guid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AnswerFriendNotify::clear_has_dst_guid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AnswerFriendNotify::clear_dst_guid() {
  dst_guid_ = GOOGLE_LONGLONG(0);
  clear_has_dst_guid();
}
inline ::google::protobuf::int64 AnswerFriendNotify::dst_guid() const {
  return dst_guid_;
}
inline void AnswerFriendNotify::set_dst_guid(::google::protobuf::int64 value) {
  set_has_dst_guid();
  dst_guid_ = value;
}

// required bool accept_flag = 2;
inline bool AnswerFriendNotify::has_accept_flag() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AnswerFriendNotify::set_has_accept_flag() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AnswerFriendNotify::clear_has_accept_flag() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AnswerFriendNotify::clear_accept_flag() {
  accept_flag_ = false;
  clear_has_accept_flag();
}
inline bool AnswerFriendNotify::accept_flag() const {
  return accept_flag_;
}
inline void AnswerFriendNotify::set_accept_flag(bool value) {
  set_has_accept_flag();
  accept_flag_ = value;
}

// optional string dst_name = 3;
inline bool AnswerFriendNotify::has_dst_name() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AnswerFriendNotify::set_has_dst_name() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AnswerFriendNotify::clear_has_dst_name() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AnswerFriendNotify::clear_dst_name() {
  if (dst_name_ != &::google::protobuf::internal::kEmptyString) {
    dst_name_->clear();
  }
  clear_has_dst_name();
}
inline const ::std::string& AnswerFriendNotify::dst_name() const {
  return *dst_name_;
}
inline void AnswerFriendNotify::set_dst_name(const ::std::string& value) {
  set_has_dst_name();
  if (dst_name_ == &::google::protobuf::internal::kEmptyString) {
    dst_name_ = new ::std::string;
  }
  dst_name_->assign(value);
}
inline void AnswerFriendNotify::set_dst_name(const char* value) {
  set_has_dst_name();
  if (dst_name_ == &::google::protobuf::internal::kEmptyString) {
    dst_name_ = new ::std::string;
  }
  dst_name_->assign(value);
}
inline void AnswerFriendNotify::set_dst_name(const char* value, size_t size) {
  set_has_dst_name();
  if (dst_name_ == &::google::protobuf::internal::kEmptyString) {
    dst_name_ = new ::std::string;
  }
  dst_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* AnswerFriendNotify::mutable_dst_name() {
  set_has_dst_name();
  if (dst_name_ == &::google::protobuf::internal::kEmptyString) {
    dst_name_ = new ::std::string;
  }
  return dst_name_;
}
inline ::std::string* AnswerFriendNotify::release_dst_name() {
  clear_has_dst_name();
  if (dst_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = dst_name_;
    dst_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional int32 dst_server_id = 4;
inline bool AnswerFriendNotify::has_dst_server_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void AnswerFriendNotify::set_has_dst_server_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void AnswerFriendNotify::clear_has_dst_server_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void AnswerFriendNotify::clear_dst_server_id() {
  dst_server_id_ = 0;
  clear_has_dst_server_id();
}
inline ::google::protobuf::int32 AnswerFriendNotify::dst_server_id() const {
  return dst_server_id_;
}
inline void AnswerFriendNotify::set_dst_server_id(::google::protobuf::int32 value) {
  set_has_dst_server_id();
  dst_server_id_ = value;
}

// -------------------------------------------------------------------

// DeleteFriendRequest

// required int64 dst_guid = 1;
inline bool DeleteFriendRequest::has_dst_guid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DeleteFriendRequest::set_has_dst_guid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DeleteFriendRequest::clear_has_dst_guid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DeleteFriendRequest::clear_dst_guid() {
  dst_guid_ = GOOGLE_LONGLONG(0);
  clear_has_dst_guid();
}
inline ::google::protobuf::int64 DeleteFriendRequest::dst_guid() const {
  return dst_guid_;
}
inline void DeleteFriendRequest::set_dst_guid(::google::protobuf::int64 value) {
  set_has_dst_guid();
  dst_guid_ = value;
}

// -------------------------------------------------------------------

// DeleteFriendResponse

// required int32 error_code = 1;
inline bool DeleteFriendResponse::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DeleteFriendResponse::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DeleteFriendResponse::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DeleteFriendResponse::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 DeleteFriendResponse::error_code() const {
  return error_code_;
}
inline void DeleteFriendResponse::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
}

// -------------------------------------------------------------------

// DeleteFriendNotify

// required int64 src_guid = 1;
inline bool DeleteFriendNotify::has_src_guid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DeleteFriendNotify::set_has_src_guid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DeleteFriendNotify::clear_has_src_guid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DeleteFriendNotify::clear_src_guid() {
  src_guid_ = GOOGLE_LONGLONG(0);
  clear_has_src_guid();
}
inline ::google::protobuf::int64 DeleteFriendNotify::src_guid() const {
  return src_guid_;
}
inline void DeleteFriendNotify::set_src_guid(::google::protobuf::int64 value) {
  set_has_src_guid();
  src_guid_ = value;
}

// -------------------------------------------------------------------

// FriendStatusNotify

// optional int64 guid = 1;
inline bool FriendStatusNotify::has_guid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FriendStatusNotify::set_has_guid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FriendStatusNotify::clear_has_guid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FriendStatusNotify::clear_guid() {
  guid_ = GOOGLE_LONGLONG(0);
  clear_has_guid();
}
inline ::google::protobuf::int64 FriendStatusNotify::guid() const {
  return guid_;
}
inline void FriendStatusNotify::set_guid(::google::protobuf::int64 value) {
  set_has_guid();
  guid_ = value;
}

// optional int32 status = 2;
inline bool FriendStatusNotify::has_status() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FriendStatusNotify::set_has_status() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FriendStatusNotify::clear_has_status() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FriendStatusNotify::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 FriendStatusNotify::status() const {
  return status_;
}
inline void FriendStatusNotify::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
}

// -------------------------------------------------------------------

// FindPlayerRequest

// optional string name = 1;
inline bool FindPlayerRequest::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FindPlayerRequest::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FindPlayerRequest::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FindPlayerRequest::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& FindPlayerRequest::name() const {
  return *name_;
}
inline void FindPlayerRequest::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void FindPlayerRequest::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void FindPlayerRequest::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* FindPlayerRequest::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* FindPlayerRequest::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// FindPlayerResponse

// required int32 error_code = 1;
inline bool FindPlayerResponse::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FindPlayerResponse::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FindPlayerResponse::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FindPlayerResponse::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 FindPlayerResponse::error_code() const {
  return error_code_;
}
inline void FindPlayerResponse::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
}

// repeated int64 guid_list = 2;
inline int FindPlayerResponse::guid_list_size() const {
  return guid_list_.size();
}
inline void FindPlayerResponse::clear_guid_list() {
  guid_list_.Clear();
}
inline ::google::protobuf::int64 FindPlayerResponse::guid_list(int index) const {
  return guid_list_.Get(index);
}
inline void FindPlayerResponse::set_guid_list(int index, ::google::protobuf::int64 value) {
  guid_list_.Set(index, value);
}
inline void FindPlayerResponse::add_guid_list(::google::protobuf::int64 value) {
  guid_list_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
FindPlayerResponse::guid_list() const {
  return guid_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
FindPlayerResponse::mutable_guid_list() {
  return &guid_list_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace common
}  // namespace protocols

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_game_5ffriend_2eproto__INCLUDED
