// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_mail.proto

#ifndef PROTOBUF_game_5fmail_2eproto__INCLUDED
#define PROTOBUF_game_5fmail_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "game_common.pb.h"
// @@protoc_insertion_point(includes)

namespace protocols {
namespace common {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_game_5fmail_2eproto();
void protobuf_AssignDesc_game_5fmail_2eproto();
void protobuf_ShutdownFile_game_5fmail_2eproto();

class MailItem;
class MailInfo;
class UpdateMailRequest;
class UpdateMailResponse;
class GetMailListRequest;
class GetMailListResponse;

enum MailUpdateType {
  MAIL_UPDATE_READ = 1,
  MAIL_UPDATE_GET_ITEM = 2,
  MAIL_UPDATE_DELETE = 3
};
bool MailUpdateType_IsValid(int value);
const MailUpdateType MailUpdateType_MIN = MAIL_UPDATE_READ;
const MailUpdateType MailUpdateType_MAX = MAIL_UPDATE_DELETE;
const int MailUpdateType_ARRAYSIZE = MailUpdateType_MAX + 1;

const ::google::protobuf::EnumDescriptor* MailUpdateType_descriptor();
inline const ::std::string& MailUpdateType_Name(MailUpdateType value) {
  return ::google::protobuf::internal::NameOfEnum(
    MailUpdateType_descriptor(), value);
}
inline bool MailUpdateType_Parse(
    const ::std::string& name, MailUpdateType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MailUpdateType>(
    MailUpdateType_descriptor(), name, value);
}
// ===================================================================

class MailItem : public ::google::protobuf::Message {
 public:
  MailItem();
  virtual ~MailItem();
  
  MailItem(const MailItem& from);
  
  inline MailItem& operator=(const MailItem& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MailItem& default_instance();
  
  void Swap(MailItem* other);
  
  // implements Message ----------------------------------------------
  
  MailItem* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MailItem& from);
  void MergeFrom(const MailItem& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 item_tid = 1 [default = 0];
  inline bool has_item_tid() const;
  inline void clear_item_tid();
  static const int kItemTidFieldNumber = 1;
  inline ::google::protobuf::int32 item_tid() const;
  inline void set_item_tid(::google::protobuf::int32 value);
  
  // optional int32 item_count = 2 [default = 0];
  inline bool has_item_count() const;
  inline void clear_item_count();
  static const int kItemCountFieldNumber = 2;
  inline ::google::protobuf::int32 item_count() const;
  inline void set_item_count(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:protocols.common.MailItem)
 private:
  inline void set_has_item_tid();
  inline void clear_has_item_tid();
  inline void set_has_item_count();
  inline void clear_has_item_count();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 item_tid_;
  ::google::protobuf::int32 item_count_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5fmail_2eproto();
  friend void protobuf_AssignDesc_game_5fmail_2eproto();
  friend void protobuf_ShutdownFile_game_5fmail_2eproto();
  
  void InitAsDefaultInstance();
  static MailItem* default_instance_;
};
// -------------------------------------------------------------------

class MailInfo : public ::google::protobuf::Message {
 public:
  MailInfo();
  virtual ~MailInfo();
  
  MailInfo(const MailInfo& from);
  
  inline MailInfo& operator=(const MailInfo& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MailInfo& default_instance();
  
  void Swap(MailInfo* other);
  
  // implements Message ----------------------------------------------
  
  MailInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MailInfo& from);
  void MergeFrom(const MailInfo& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 mail_id = 1;
  inline bool has_mail_id() const;
  inline void clear_mail_id();
  static const int kMailIdFieldNumber = 1;
  inline ::google::protobuf::int32 mail_id() const;
  inline void set_mail_id(::google::protobuf::int32 value);
  
  // optional int32 src_role_id = 2;
  inline bool has_src_role_id() const;
  inline void clear_src_role_id();
  static const int kSrcRoleIdFieldNumber = 2;
  inline ::google::protobuf::int32 src_role_id() const;
  inline void set_src_role_id(::google::protobuf::int32 value);
  
  // optional int32 create_time = 3;
  inline bool has_create_time() const;
  inline void clear_create_time();
  static const int kCreateTimeFieldNumber = 3;
  inline ::google::protobuf::int32 create_time() const;
  inline void set_create_time(::google::protobuf::int32 value);
  
  // optional int32 status = 4;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 4;
  inline ::google::protobuf::int32 status() const;
  inline void set_status(::google::protobuf::int32 value);
  
  // optional string src_name = 5;
  inline bool has_src_name() const;
  inline void clear_src_name();
  static const int kSrcNameFieldNumber = 5;
  inline const ::std::string& src_name() const;
  inline void set_src_name(const ::std::string& value);
  inline void set_src_name(const char* value);
  inline void set_src_name(const char* value, size_t size);
  inline ::std::string* mutable_src_name();
  inline ::std::string* release_src_name();
  
  // optional string title = 6;
  inline bool has_title() const;
  inline void clear_title();
  static const int kTitleFieldNumber = 6;
  inline const ::std::string& title() const;
  inline void set_title(const ::std::string& value);
  inline void set_title(const char* value);
  inline void set_title(const char* value, size_t size);
  inline ::std::string* mutable_title();
  inline ::std::string* release_title();
  
  // optional string content = 7;
  inline bool has_content() const;
  inline void clear_content();
  static const int kContentFieldNumber = 7;
  inline const ::std::string& content() const;
  inline void set_content(const ::std::string& value);
  inline void set_content(const char* value);
  inline void set_content(const char* value, size_t size);
  inline ::std::string* mutable_content();
  inline ::std::string* release_content();
  
  // optional int32 attach_flag = 9;
  inline bool has_attach_flag() const;
  inline void clear_attach_flag();
  static const int kAttachFlagFieldNumber = 9;
  inline ::google::protobuf::int32 attach_flag() const;
  inline void set_attach_flag(::google::protobuf::int32 value);
  
  // repeated .protocols.common.MailItem item_list = 12;
  inline int item_list_size() const;
  inline void clear_item_list();
  static const int kItemListFieldNumber = 12;
  inline const ::protocols::common::MailItem& item_list(int index) const;
  inline ::protocols::common::MailItem* mutable_item_list(int index);
  inline ::protocols::common::MailItem* add_item_list();
  inline const ::google::protobuf::RepeatedPtrField< ::protocols::common::MailItem >&
      item_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::protocols::common::MailItem >*
      mutable_item_list();
  
  // optional .protocols.common.BankInfo money = 13;
  inline bool has_money() const;
  inline void clear_money();
  static const int kMoneyFieldNumber = 13;
  inline const ::protocols::common::BankInfo& money() const;
  inline ::protocols::common::BankInfo* mutable_money();
  inline ::protocols::common::BankInfo* release_money();
  
  // @@protoc_insertion_point(class_scope:protocols.common.MailInfo)
 private:
  inline void set_has_mail_id();
  inline void clear_has_mail_id();
  inline void set_has_src_role_id();
  inline void clear_has_src_role_id();
  inline void set_has_create_time();
  inline void clear_has_create_time();
  inline void set_has_status();
  inline void clear_has_status();
  inline void set_has_src_name();
  inline void clear_has_src_name();
  inline void set_has_title();
  inline void clear_has_title();
  inline void set_has_content();
  inline void clear_has_content();
  inline void set_has_attach_flag();
  inline void clear_has_attach_flag();
  inline void set_has_money();
  inline void clear_has_money();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 mail_id_;
  ::google::protobuf::int32 src_role_id_;
  ::google::protobuf::int32 create_time_;
  ::google::protobuf::int32 status_;
  ::std::string* src_name_;
  ::std::string* title_;
  ::std::string* content_;
  ::google::protobuf::RepeatedPtrField< ::protocols::common::MailItem > item_list_;
  ::protocols::common::BankInfo* money_;
  ::google::protobuf::int32 attach_flag_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(10 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5fmail_2eproto();
  friend void protobuf_AssignDesc_game_5fmail_2eproto();
  friend void protobuf_ShutdownFile_game_5fmail_2eproto();
  
  void InitAsDefaultInstance();
  static MailInfo* default_instance_;
};
// -------------------------------------------------------------------

class UpdateMailRequest : public ::google::protobuf::Message {
 public:
  UpdateMailRequest();
  virtual ~UpdateMailRequest();
  
  UpdateMailRequest(const UpdateMailRequest& from);
  
  inline UpdateMailRequest& operator=(const UpdateMailRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdateMailRequest& default_instance();
  
  void Swap(UpdateMailRequest* other);
  
  // implements Message ----------------------------------------------
  
  UpdateMailRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UpdateMailRequest& from);
  void MergeFrom(const UpdateMailRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated int32 mail_list = 3;
  inline int mail_list_size() const;
  inline void clear_mail_list();
  static const int kMailListFieldNumber = 3;
  inline ::google::protobuf::int32 mail_list(int index) const;
  inline void set_mail_list(int index, ::google::protobuf::int32 value);
  inline void add_mail_list(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      mail_list() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_mail_list();
  
  // optional int32 update_type = 2;
  inline bool has_update_type() const;
  inline void clear_update_type();
  static const int kUpdateTypeFieldNumber = 2;
  inline ::google::protobuf::int32 update_type() const;
  inline void set_update_type(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:protocols.common.UpdateMailRequest)
 private:
  inline void set_has_update_type();
  inline void clear_has_update_type();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > mail_list_;
  ::google::protobuf::int32 update_type_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5fmail_2eproto();
  friend void protobuf_AssignDesc_game_5fmail_2eproto();
  friend void protobuf_ShutdownFile_game_5fmail_2eproto();
  
  void InitAsDefaultInstance();
  static UpdateMailRequest* default_instance_;
};
// -------------------------------------------------------------------

class UpdateMailResponse : public ::google::protobuf::Message {
 public:
  UpdateMailResponse();
  virtual ~UpdateMailResponse();
  
  UpdateMailResponse(const UpdateMailResponse& from);
  
  inline UpdateMailResponse& operator=(const UpdateMailResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdateMailResponse& default_instance();
  
  void Swap(UpdateMailResponse* other);
  
  // implements Message ----------------------------------------------
  
  UpdateMailResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UpdateMailResponse& from);
  void MergeFrom(const UpdateMailResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 error_code = 1;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::int32 error_code() const;
  inline void set_error_code(::google::protobuf::int32 value);
  
  // optional int32 update_type = 2;
  inline bool has_update_type() const;
  inline void clear_update_type();
  static const int kUpdateTypeFieldNumber = 2;
  inline ::google::protobuf::int32 update_type() const;
  inline void set_update_type(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:protocols.common.UpdateMailResponse)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();
  inline void set_has_update_type();
  inline void clear_has_update_type();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 error_code_;
  ::google::protobuf::int32 update_type_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5fmail_2eproto();
  friend void protobuf_AssignDesc_game_5fmail_2eproto();
  friend void protobuf_ShutdownFile_game_5fmail_2eproto();
  
  void InitAsDefaultInstance();
  static UpdateMailResponse* default_instance_;
};
// -------------------------------------------------------------------

class GetMailListRequest : public ::google::protobuf::Message {
 public:
  GetMailListRequest();
  virtual ~GetMailListRequest();
  
  GetMailListRequest(const GetMailListRequest& from);
  
  inline GetMailListRequest& operator=(const GetMailListRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetMailListRequest& default_instance();
  
  void Swap(GetMailListRequest* other);
  
  // implements Message ----------------------------------------------
  
  GetMailListRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetMailListRequest& from);
  void MergeFrom(const GetMailListRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:protocols.common.GetMailListRequest)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];
  
  friend void  protobuf_AddDesc_game_5fmail_2eproto();
  friend void protobuf_AssignDesc_game_5fmail_2eproto();
  friend void protobuf_ShutdownFile_game_5fmail_2eproto();
  
  void InitAsDefaultInstance();
  static GetMailListRequest* default_instance_;
};
// -------------------------------------------------------------------

class GetMailListResponse : public ::google::protobuf::Message {
 public:
  GetMailListResponse();
  virtual ~GetMailListResponse();
  
  GetMailListResponse(const GetMailListResponse& from);
  
  inline GetMailListResponse& operator=(const GetMailListResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetMailListResponse& default_instance();
  
  void Swap(GetMailListResponse* other);
  
  // implements Message ----------------------------------------------
  
  GetMailListResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetMailListResponse& from);
  void MergeFrom(const GetMailListResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 error_code = 1;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::int32 error_code() const;
  inline void set_error_code(::google::protobuf::int32 value);
  
  // repeated .protocols.common.MailInfo mail_list = 2;
  inline int mail_list_size() const;
  inline void clear_mail_list();
  static const int kMailListFieldNumber = 2;
  inline const ::protocols::common::MailInfo& mail_list(int index) const;
  inline ::protocols::common::MailInfo* mutable_mail_list(int index);
  inline ::protocols::common::MailInfo* add_mail_list();
  inline const ::google::protobuf::RepeatedPtrField< ::protocols::common::MailInfo >&
      mail_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::protocols::common::MailInfo >*
      mutable_mail_list();
  
  // @@protoc_insertion_point(class_scope:protocols.common.GetMailListResponse)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::protocols::common::MailInfo > mail_list_;
  ::google::protobuf::int32 error_code_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5fmail_2eproto();
  friend void protobuf_AssignDesc_game_5fmail_2eproto();
  friend void protobuf_ShutdownFile_game_5fmail_2eproto();
  
  void InitAsDefaultInstance();
  static GetMailListResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// MailItem

// optional int32 item_tid = 1 [default = 0];
inline bool MailItem::has_item_tid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MailItem::set_has_item_tid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MailItem::clear_has_item_tid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MailItem::clear_item_tid() {
  item_tid_ = 0;
  clear_has_item_tid();
}
inline ::google::protobuf::int32 MailItem::item_tid() const {
  return item_tid_;
}
inline void MailItem::set_item_tid(::google::protobuf::int32 value) {
  set_has_item_tid();
  item_tid_ = value;
}

// optional int32 item_count = 2 [default = 0];
inline bool MailItem::has_item_count() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MailItem::set_has_item_count() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MailItem::clear_has_item_count() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MailItem::clear_item_count() {
  item_count_ = 0;
  clear_has_item_count();
}
inline ::google::protobuf::int32 MailItem::item_count() const {
  return item_count_;
}
inline void MailItem::set_item_count(::google::protobuf::int32 value) {
  set_has_item_count();
  item_count_ = value;
}

// -------------------------------------------------------------------

// MailInfo

// optional int32 mail_id = 1;
inline bool MailInfo::has_mail_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MailInfo::set_has_mail_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MailInfo::clear_has_mail_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MailInfo::clear_mail_id() {
  mail_id_ = 0;
  clear_has_mail_id();
}
inline ::google::protobuf::int32 MailInfo::mail_id() const {
  return mail_id_;
}
inline void MailInfo::set_mail_id(::google::protobuf::int32 value) {
  set_has_mail_id();
  mail_id_ = value;
}

// optional int32 src_role_id = 2;
inline bool MailInfo::has_src_role_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MailInfo::set_has_src_role_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MailInfo::clear_has_src_role_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MailInfo::clear_src_role_id() {
  src_role_id_ = 0;
  clear_has_src_role_id();
}
inline ::google::protobuf::int32 MailInfo::src_role_id() const {
  return src_role_id_;
}
inline void MailInfo::set_src_role_id(::google::protobuf::int32 value) {
  set_has_src_role_id();
  src_role_id_ = value;
}

// optional int32 create_time = 3;
inline bool MailInfo::has_create_time() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MailInfo::set_has_create_time() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MailInfo::clear_has_create_time() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MailInfo::clear_create_time() {
  create_time_ = 0;
  clear_has_create_time();
}
inline ::google::protobuf::int32 MailInfo::create_time() const {
  return create_time_;
}
inline void MailInfo::set_create_time(::google::protobuf::int32 value) {
  set_has_create_time();
  create_time_ = value;
}

// optional int32 status = 4;
inline bool MailInfo::has_status() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MailInfo::set_has_status() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MailInfo::clear_has_status() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MailInfo::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 MailInfo::status() const {
  return status_;
}
inline void MailInfo::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
}

// optional string src_name = 5;
inline bool MailInfo::has_src_name() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MailInfo::set_has_src_name() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MailInfo::clear_has_src_name() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MailInfo::clear_src_name() {
  if (src_name_ != &::google::protobuf::internal::kEmptyString) {
    src_name_->clear();
  }
  clear_has_src_name();
}
inline const ::std::string& MailInfo::src_name() const {
  return *src_name_;
}
inline void MailInfo::set_src_name(const ::std::string& value) {
  set_has_src_name();
  if (src_name_ == &::google::protobuf::internal::kEmptyString) {
    src_name_ = new ::std::string;
  }
  src_name_->assign(value);
}
inline void MailInfo::set_src_name(const char* value) {
  set_has_src_name();
  if (src_name_ == &::google::protobuf::internal::kEmptyString) {
    src_name_ = new ::std::string;
  }
  src_name_->assign(value);
}
inline void MailInfo::set_src_name(const char* value, size_t size) {
  set_has_src_name();
  if (src_name_ == &::google::protobuf::internal::kEmptyString) {
    src_name_ = new ::std::string;
  }
  src_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MailInfo::mutable_src_name() {
  set_has_src_name();
  if (src_name_ == &::google::protobuf::internal::kEmptyString) {
    src_name_ = new ::std::string;
  }
  return src_name_;
}
inline ::std::string* MailInfo::release_src_name() {
  clear_has_src_name();
  if (src_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = src_name_;
    src_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional string title = 6;
inline bool MailInfo::has_title() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void MailInfo::set_has_title() {
  _has_bits_[0] |= 0x00000020u;
}
inline void MailInfo::clear_has_title() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void MailInfo::clear_title() {
  if (title_ != &::google::protobuf::internal::kEmptyString) {
    title_->clear();
  }
  clear_has_title();
}
inline const ::std::string& MailInfo::title() const {
  return *title_;
}
inline void MailInfo::set_title(const ::std::string& value) {
  set_has_title();
  if (title_ == &::google::protobuf::internal::kEmptyString) {
    title_ = new ::std::string;
  }
  title_->assign(value);
}
inline void MailInfo::set_title(const char* value) {
  set_has_title();
  if (title_ == &::google::protobuf::internal::kEmptyString) {
    title_ = new ::std::string;
  }
  title_->assign(value);
}
inline void MailInfo::set_title(const char* value, size_t size) {
  set_has_title();
  if (title_ == &::google::protobuf::internal::kEmptyString) {
    title_ = new ::std::string;
  }
  title_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MailInfo::mutable_title() {
  set_has_title();
  if (title_ == &::google::protobuf::internal::kEmptyString) {
    title_ = new ::std::string;
  }
  return title_;
}
inline ::std::string* MailInfo::release_title() {
  clear_has_title();
  if (title_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = title_;
    title_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional string content = 7;
inline bool MailInfo::has_content() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void MailInfo::set_has_content() {
  _has_bits_[0] |= 0x00000040u;
}
inline void MailInfo::clear_has_content() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void MailInfo::clear_content() {
  if (content_ != &::google::protobuf::internal::kEmptyString) {
    content_->clear();
  }
  clear_has_content();
}
inline const ::std::string& MailInfo::content() const {
  return *content_;
}
inline void MailInfo::set_content(const ::std::string& value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(value);
}
inline void MailInfo::set_content(const char* value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(value);
}
inline void MailInfo::set_content(const char* value, size_t size) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MailInfo::mutable_content() {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  return content_;
}
inline ::std::string* MailInfo::release_content() {
  clear_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = content_;
    content_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional int32 attach_flag = 9;
inline bool MailInfo::has_attach_flag() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void MailInfo::set_has_attach_flag() {
  _has_bits_[0] |= 0x00000080u;
}
inline void MailInfo::clear_has_attach_flag() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void MailInfo::clear_attach_flag() {
  attach_flag_ = 0;
  clear_has_attach_flag();
}
inline ::google::protobuf::int32 MailInfo::attach_flag() const {
  return attach_flag_;
}
inline void MailInfo::set_attach_flag(::google::protobuf::int32 value) {
  set_has_attach_flag();
  attach_flag_ = value;
}

// repeated .protocols.common.MailItem item_list = 12;
inline int MailInfo::item_list_size() const {
  return item_list_.size();
}
inline void MailInfo::clear_item_list() {
  item_list_.Clear();
}
inline const ::protocols::common::MailItem& MailInfo::item_list(int index) const {
  return item_list_.Get(index);
}
inline ::protocols::common::MailItem* MailInfo::mutable_item_list(int index) {
  return item_list_.Mutable(index);
}
inline ::protocols::common::MailItem* MailInfo::add_item_list() {
  return item_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::protocols::common::MailItem >&
MailInfo::item_list() const {
  return item_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::protocols::common::MailItem >*
MailInfo::mutable_item_list() {
  return &item_list_;
}

// optional .protocols.common.BankInfo money = 13;
inline bool MailInfo::has_money() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void MailInfo::set_has_money() {
  _has_bits_[0] |= 0x00000200u;
}
inline void MailInfo::clear_has_money() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void MailInfo::clear_money() {
  if (money_ != NULL) money_->::protocols::common::BankInfo::Clear();
  clear_has_money();
}
inline const ::protocols::common::BankInfo& MailInfo::money() const {
  return money_ != NULL ? *money_ : *default_instance_->money_;
}
inline ::protocols::common::BankInfo* MailInfo::mutable_money() {
  set_has_money();
  if (money_ == NULL) money_ = new ::protocols::common::BankInfo;
  return money_;
}
inline ::protocols::common::BankInfo* MailInfo::release_money() {
  clear_has_money();
  ::protocols::common::BankInfo* temp = money_;
  money_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// UpdateMailRequest

// repeated int32 mail_list = 3;
inline int UpdateMailRequest::mail_list_size() const {
  return mail_list_.size();
}
inline void UpdateMailRequest::clear_mail_list() {
  mail_list_.Clear();
}
inline ::google::protobuf::int32 UpdateMailRequest::mail_list(int index) const {
  return mail_list_.Get(index);
}
inline void UpdateMailRequest::set_mail_list(int index, ::google::protobuf::int32 value) {
  mail_list_.Set(index, value);
}
inline void UpdateMailRequest::add_mail_list(::google::protobuf::int32 value) {
  mail_list_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
UpdateMailRequest::mail_list() const {
  return mail_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
UpdateMailRequest::mutable_mail_list() {
  return &mail_list_;
}

// optional int32 update_type = 2;
inline bool UpdateMailRequest::has_update_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UpdateMailRequest::set_has_update_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UpdateMailRequest::clear_has_update_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UpdateMailRequest::clear_update_type() {
  update_type_ = 0;
  clear_has_update_type();
}
inline ::google::protobuf::int32 UpdateMailRequest::update_type() const {
  return update_type_;
}
inline void UpdateMailRequest::set_update_type(::google::protobuf::int32 value) {
  set_has_update_type();
  update_type_ = value;
}

// -------------------------------------------------------------------

// UpdateMailResponse

// required int32 error_code = 1;
inline bool UpdateMailResponse::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UpdateMailResponse::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UpdateMailResponse::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UpdateMailResponse::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 UpdateMailResponse::error_code() const {
  return error_code_;
}
inline void UpdateMailResponse::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
}

// optional int32 update_type = 2;
inline bool UpdateMailResponse::has_update_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UpdateMailResponse::set_has_update_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UpdateMailResponse::clear_has_update_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UpdateMailResponse::clear_update_type() {
  update_type_ = 0;
  clear_has_update_type();
}
inline ::google::protobuf::int32 UpdateMailResponse::update_type() const {
  return update_type_;
}
inline void UpdateMailResponse::set_update_type(::google::protobuf::int32 value) {
  set_has_update_type();
  update_type_ = value;
}

// -------------------------------------------------------------------

// GetMailListRequest

// -------------------------------------------------------------------

// GetMailListResponse

// required int32 error_code = 1;
inline bool GetMailListResponse::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetMailListResponse::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetMailListResponse::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetMailListResponse::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 GetMailListResponse::error_code() const {
  return error_code_;
}
inline void GetMailListResponse::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
}

// repeated .protocols.common.MailInfo mail_list = 2;
inline int GetMailListResponse::mail_list_size() const {
  return mail_list_.size();
}
inline void GetMailListResponse::clear_mail_list() {
  mail_list_.Clear();
}
inline const ::protocols::common::MailInfo& GetMailListResponse::mail_list(int index) const {
  return mail_list_.Get(index);
}
inline ::protocols::common::MailInfo* GetMailListResponse::mutable_mail_list(int index) {
  return mail_list_.Mutable(index);
}
inline ::protocols::common::MailInfo* GetMailListResponse::add_mail_list() {
  return mail_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::protocols::common::MailInfo >&
GetMailListResponse::mail_list() const {
  return mail_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::protocols::common::MailInfo >*
GetMailListResponse::mutable_mail_list() {
  return &mail_list_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace common
}  // namespace protocols

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< protocols::common::MailUpdateType>() {
  return protocols::common::MailUpdateType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_game_5fmail_2eproto__INCLUDED
